"""cascade paid subs and videos

Revision ID: 52c3a21e8954
Revises: b2022158756e
Create Date: 2025-12-18 12:41:17.513240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52c3a21e8954"
down_revision: Union[str, Sequence[str], None] = "b2022158756e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_channel_strikes_video_id_videos"),
        "channel_strikes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_channel_strikes_video_id_videos"),
        "channel_strikes",
        "videos",
        ["video_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_paid_subscriptions_sub_user_id_subscription"),
        "paid_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_paid_subscriptions_sub_user_id_subscription"),
        "paid_subscriptions",
        "subscription",
        ["sub_user_id", "sub_channel_id"],
        ["user_id", "channel_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_paid_subscriptions_sub_user_id_subscription"),
        "paid_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_paid_subscriptions_sub_user_id_subscription"),
        "paid_subscriptions",
        "subscription",
        ["sub_user_id", "sub_channel_id"],
        ["user_id", "channel_id"],
    )
    op.drop_constraint(
        op.f("fk_channel_strikes_video_id_videos"),
        "channel_strikes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_channel_strikes_video_id_videos"),
        "channel_strikes",
        "videos",
        ["video_id"],
        ["id"],
    )
    # ### end Alembic commands ###
