"""delete_moderators_table

Revision ID: 637eb2f37f94
Revises: 298b5cad6f37
Create Date: 2025-12-14 18:52:49.638790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637eb2f37f94'
down_revision: Union[str, Sequence[str], None] = '298b5cad6f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderators')
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    op.create_table('moderators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_moderators_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', name=op.f('pk_moderators'))
    )
    # ### end Alembic commands ###
