"""add indexes

Revision ID: 9102b6b4e0b3
Revises: b2022158756e
Create Date: 2025-12-18 11:49:51.416670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9102b6b4e0b3'
down_revision: Union[str, Sequence[str], None] = 'b2022158756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_channel_strikes_channel_id'), 'channel_strikes', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channels_owner_id'), 'channels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_comments_commented_at'), 'comments', ['commented_at'], unique=False)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_index(op.f('ix_playlists_author_id'), 'playlists', ['author_id'], unique=False)
    op.create_index(op.f('ix_reports_is_resolved'), 'reports', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_video_id'), 'reports', ['video_id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_is_active'), 'videos', ['is_active'], unique=False)
    op.create_index(op.f('ix_views_watched_at'), 'views', ['watched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_views_watched_at'), table_name='views')
    op.drop_index(op.f('ix_videos_is_active'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_reports_video_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_resolved'), table_name='reports')
    op.drop_index(op.f('ix_playlists_author_id'), table_name='playlists')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_commented_at'), table_name='comments')
    op.drop_index(op.f('ix_channels_owner_id'), table_name='channels')
    op.drop_index(op.f('ix_channel_strikes_channel_id'), table_name='channel_strikes')
    # ### end Alembic commands ###
