"""field_added_in_view_class

Revision ID: abc1af6f4bc4
Revises: 068dfb6f7dcc
Create Date: 2025-12-17 21:49:23.280548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc1af6f4bc4'
down_revision: Union[str, Sequence[str], None] = '068dfb6f7dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views', sa.Column('watched_percentage', sa.Float(), nullable=False, server_default="0.0"))
    op.add_column('views', sa.Column('reaction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views', 'reaction')
    op.drop_column('views', 'watched_percentage')
    # ### end Alembic commands ###
