"""add paid subscriptions and strikes

Revision ID: b2022158756e
Revises: abc1af6f4bc4
Create Date: 2025-12-17 23:35:36.677904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2022158756e'
down_revision: Union[str, Sequence[str], None] = 'abc1af6f4bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_strikes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_strikes_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_channel_strikes_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_strikes'))
    )
    op.create_table('paid_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active_since', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_to', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'DIAMOND', name='paidsubtier'), nullable=False),
    sa.Column('sub_user_id', sa.Integer(), nullable=False),
    sa.Column('sub_channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_user_id', 'sub_channel_id'], ['subscription.user_id', 'subscription.channel_id'], name=op.f('fk_paid_subscriptions_sub_user_id_subscription')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paid_subscriptions'))
    )
    op.drop_column('channels', 'strikes')
    op.add_column('subscription', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_active')
    op.add_column('channels', sa.Column('strikes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('paid_subscriptions')
    op.drop_table('channel_strikes')
    # ### end Alembic commands ###
