"""admin_features

Revision ID: e55407c3fe66
Revises: ed806f6b6b47
Create Date: 2025-12-17 12:36:17.055254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55407c3fe66'
down_revision: Union[str, Sequence[str], None] = 'ed806f6b6b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(reason) <= 512', name=op.f('ck_reports_ck_reports_reason_length')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_reports_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.add_column('channels', sa.Column('strikes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('videos', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('videos', sa.Column('is_monetized', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_monetized')
    op.drop_column('videos', 'is_active')
    op.drop_column('users', 'is_banned')
    op.drop_column('channels', 'strikes')
    op.drop_table('reports')
    # ### end Alembic commands ###
