"""add paid subscriptions and strikes

Revision ID: ec99b1075775
Revises: 637eb2f37f94
Create Date: 2025-12-16 16:09:15.094156

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec99b1075775"
down_revision: Union[str, Sequence[str], None] = "637eb2f37f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_strikes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_channel_strikes_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_channel_strikes_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_strikes")),
    )
    op.create_table(
        "paid_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "active_since",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "active_to", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "tier",
            sa.Enum("BRONZE", "SILVER", "GOLD", "DIAMOND", name="paidsubtier"),
            nullable=False,
        ),
        sa.Column("sub_user_id", sa.Integer(), nullable=False),
        sa.Column("sub_channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sub_user_id", "sub_channel_id"],
            ["subscription.user_id", "subscription.channel_id"],
            name=op.f("fk_paid_subscriptions_sub_user_id_subscription"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paid_subscriptions")),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "is_active")
    op.drop_table("paid_subscriptions")
    op.drop_table("channel_strikes")
    # ### end Alembic commands ###
